name: ServerCore
main: iiFouzi\ServerCore\Main
api: [3.0.0, 4.0.0]
version: 1.0.0
author: "iiFouzi"

commands:
 heal:
  description: "heal you"
 feed:
  description: "feed you"
 fly:
  description: "enable your fly ability"
 ci:
  description: "clear your inventory"
 ping:
  description: "shows ur ping/latency"
  
permissions:
 servercore.heal:
  default: op
 servercore.feed:
  default: op
 servercore.fly:
  default: op
 servercore.ci:
  default: op
